# Generated by Django 4.2.4 on 2025-04-27 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recepies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'custom_user',
                'managed': True,
            },
            managers=[
                ('objects', recepies.models.NewUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('approving_date', models.DateField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('registered', 'Зарегистрирован'), ('moderating', 'Проверяется'), ('approved', 'Принято'), ('denied', 'Отказано'), ('deleted', 'Удалено')], max_length=32, null=True)),
                ('ready_status', models.BooleanField(default=False, null=True)),
                ('id_moderator', models.ForeignKey(blank=True, db_column='id_moderator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_application', to=settings.AUTH_USER_MODEL)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='user_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=64, null=True)),
                ('product_info', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(blank=True, choices=[('enabled', 'enabled'), ('deleted', 'deleted')], max_length=32, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.IntegerField(default=0)),
                ('rating', models.FloatField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_claim', models.CharField(blank=True, max_length=128)),
                ('text_claim', models.CharField(blank=True, max_length=512, null=True)),
                ('admin_text_claim', models.CharField(blank=True, max_length=512, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('approving_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('publicated', 'Опубликовано'), ('reviewed', 'Рассмотрено'), ('deleted', 'Удалено')], max_length=16, null=True)),
                ('id_moderator', models.ForeignKey(blank=True, db_column='id_moderator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_claim', to=settings.AUTH_USER_MODEL)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='user_claim', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='recepies.application')),
                ('products', models.ForeignKey(db_column='products_id', on_delete=django.db.models.deletion.DO_NOTHING, to='recepies.products')),
            ],
            options={
                'db_table': 'application_products',
                'managed': True,
                'unique_together': {('application', 'products')},
            },
        ),
    ]
