# Generated by Django 4.2.8 on 2023-12-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
