# Generated by Django 4.2.7 on 2023-12-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0002_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='paid_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
