# Generated by Django 4.2.7 on 2023-12-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0003_application_paid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='paid_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
