# Generated by Django 4.2.7 on 2023-12-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0005_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='paid_status',
        ),
    ]
