# Generated by Django 4.2.7 on 2023-12-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0006_remove_application_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ready_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
