# Generated by Django 4.2.7 on 2025-01-12 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0007_application_ready_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textClaim', models.CharField(blank=True, max_length=512, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('id_moderator', models.ForeignKey(blank=True, db_column='id_moderator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_claim', to=settings.AUTH_USER_MODEL)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='user_claim', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
