# Generated by Django 4.2.7 on 2025-01-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0008_claim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='textClaim',
            new_name='text_сlaim',
        ),
        migrations.AddField(
            model_name='claim',
            name='approving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='status',
            field=models.CharField(blank=True, choices=[('publicated', 'Опубликовано'), ('reviewed', 'Рассмотрено'), ('deleted', 'Удалено')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='title_claim',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
