# Generated by Django 4.2.7 on 2025-03-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0009_rename_textclaim_claim_text_сlaim_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='text_сlaim',
            new_name='text_claim',
        ),
    ]
