# Generated by Django 4.2.7 on 2025-03-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0010_rename_text_сlaim_claim_text_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='admin_text_claim',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
