# Generated by Django 4.2.7 on 2025-03-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0011_claim_admin_text_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.FloatField(blank=True, max_length=16, null=True),
        ),
    ]
