# Generated by Django 4.2.7 on 2025-04-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0013_alter_products_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='photo',
        ),
    ]
